apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-app-19
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-app-19
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kadourah/dotnetappe10
      ref:
        branch: main
